pipeline {
    agent any

    stages {
        stage('Checkout') {
            steps {
                checkout scm
            }
        }

        stage('Setup Python') {
            steps {
                sh '''
                    python3 --version
                    python3 -m venv .venv
                    . .venv/bin/activate
                    python -m pip install --upgrade pip
                    pip install -r requirements.txt
                '''
            }
        }

        stage('Run RBAC Analysis') {
            steps {
                sh '''
                    . .venv/bin/activate
                    python -m src.main batch scenarios --out results
                '''
            }
        }

         stage('Security Gate') {
            steps {
                sh '''
                    . .venv/bin/activate
                    python src/ci_gate.py
                '''
            }
        }


        stage('Archive Results') {
            steps {
                archiveArtifacts artifacts: 'results/**', fingerprint: true
            }
        }
    }
}